### PR TITLE
wip: enforce black- and whitelisting from ACE3 virtual arsenal

### PR DESCRIPTION
**Pull request by matfax**
Almost complete feature. What's still wip is a visual differentiation of cases where there is only one option value, or no matching option value (due to faction filter being inconsistent with virtual arsenal filter or equipped clothing) available.

### CODE REVIEW

**Comment by jetelain** [comment]
whitelist and blacklist are defined at each arsenal instance, and should not be enforced at gearinfo level.

gearinfo is intend to be independent from arsenal stuff, it's intend be completely stateless.

**Comment by jetelain** [comment]
You're also introducing multiple unrelated features in the same PR, it's hard to understand each part.

I think values should be explicitly listed by each option, and not deducted from child classes. It was done on purpose to keep code simple.

**Comment by matfax** [comment]
First off, I really appreciate the feedback.

> You're also introducing multiple unrelated features in the same PR, it's hard to understand each part.

They were all the means to the same end. Namely to have only those values shown and reachable that reflect actually selectable and non-blacklisted configs. I just threw them all together because it's still a work in progress but separate commits make it easier to follow and trace eventual bugs that might be introduced.

> I think values should be explicitly listed by each option, and not deducted from child classes. It was done on purpose to keep code simple.

It's not really a hassle to request all child class names in a single call. It could be further improved by requesting the class configs but I didn't see any particular reason to change what already works. The dynamic values would become more important once they are further filtered or extended from a config-level, not UI-level.

> Could you make a separate PR for implicit values declaration ? to see if complexity worth it ;-)

I put the relevant commits in #26. You can squash the PR if you prefer fewer commits.

> whitelist and blacklist are defined at each arsenal instance, and should not be enforced at gearinfo level.
> 
> gearinfo is intend to be independent from arsenal stuff, it's intend be completely stateless.

That's also what I thought when considering how to design this. The issue is that in order to be accurate from a config-level, the logic needs to be integrated somehow either on the gearinfo level or in an additional layer between. The additional layer would need a lot of refactoring, as far as I can tell. If the filtering information was passed through to gearinfo instead of a global cross-reference, it would still be a lot of redundant parameter information to be added in a cross-cutting manner. Before doing this, it might be more effective to use a different method to share class- and component-level information throughout these functions, either by passing a hash map or by introducing a base class. This would also allow improved dependency management for the caches.

I would say that the problem even stems from ACE because ACE already does a lot with global variables. Either way, it requires refactoring and I'm hesitant to change a working design for a non-essential. though significant, feature.

The simplest, mostly stateless method would be a cross-cutting parameter extension to propagate the virtual arsenal instead of `EGVAR` use. To keep this extensible and decoupled from its `arsenal`-meaning, I wouldn't propagate the virtual arsenal itself but just a filtering method, which means that the variants will just provide a filtering interface.

I would also like to use this interface for faction filtering. The current approach to faction filtering is purely on a UI level and it becomes an inconsistency once blacklisting is applied as well because the faction filter doesn't apply to all options, while the blacklisting filter applies to the whole model, which means that there can be non-disabled buttons without function because the referenced option button is hidden by the faction filter. The current faction filter is in the wrong place, either way. With the dynamic values, the "filtered" factions would either be disabled (if values are defined explicitly as a superset) or not detected in the first place as a valid config value.

The only hassle in this is the caching because the caching keys have to include the filtering information somehow and it's currently done on the gearinfo level, which can violate the statelessness. I will have to see whether the mutable parts of a `code` object are recognized by `hashValue` but I doubt it. I guess that I would have to propagate the cod and parameters together, just as CBA typically does, and create a hash for this tuple.

**Comment by jetelain** [comment]
Thanks for splitting the two features.

To keep the design `gearinfo` is intended to be useful in both `arsenal` and `ingame`, it's the common logic between them. 

The biggest issue with current design proposal is that the behavior would not be consistent if you use multiple arsenal with different whitelist/blacklists. A typical case is that you have a limited arsenal for players, but for some reason you add a full arsenal to the player (because something is missing). The missing element might not be available to the player.
For the same reason some ingame actions might not be available because they was not allowed by the previous arsenal you used.

I think Whitelisting/Blacklisting could be done as a post-processing of getModelOptions result done at arsenal level, with a cache destroyed when you close the arsenal.

The real question is what do we expect from mission designer :
- should mission designer explicitly list allowed variations ?
- should he list only some base variations and we infer allowed options ?

The first option is the easiest. We filter out options values that no allowed variations.

**Comment by matfax** [comment]
> The biggest issue with current design proposal is that the behavior would not be consistent if you use multiple arsenal with different whitelist/blacklists.

That's why I integrated the virtualArsenal as cache key subject. This was part of my test scenario. You can move between different arsenals with different black-/whitelists and the cache will not be reused but a new cache will be created. Whenever an arsenal is opened, the `cacheId`, how I called it, which is the hashValue of the virtual arsenal (representing the whitelist), will be refreshed and used for further actions.

> I think Whitelisting/Blacklisting could be done as a post-processing of getModelOptions result done at arsenal level, with a cache destroyed when you close the arsenal.

The destruction of the cache was my first idea as well but the integration of the key allows the reuse of the already generated caches.

> The first option is the easiest. We filter out options values that no allowed variations.

I didn't want to interfere with the existing black- and whitelisting feature of ACE, so I chose the first option which I think is also in the interest of Zeus, mission designers, and server admins.

After the other PRs, I would first test the existing `main`, just to make sure that we didn't introduce any errors due to splitting, rebasing, or merging. Then, I would reproach this with your design concern in mind. Clearing the cache from a different package also violates the separation of concerns principle. Imho, the sophisticated way to go is to provide an interface from the variations function in the gearinfo module as a parameter, accepting a function and parameter set. This would be propagated along with the other parameters where necessary. The filtering itself would be implemented in the arsenal module. This means that everything in both modules remains separated and only reflects the own view of the decoupled logic. The caching wouldn't depend on a global variable anymore but on the given function and parameter set.

I hope this outlines it clearly. It will be even clearer once it's implemented. After this, it should be in a state where I can continue on my configs. Though there are still some issues with the texture options which might need addressing.

**Comment by matfax** [comment]
I think it was ready at some point, just never got merged. I'm closing it for now because of too many conflicts.

**Pull request closed without merging**
